In [8]:
import pandas as pd

df = pd.read_csv('../dataset/course.csv')
df.head()

,ID,Mata Kuliah,Major,Description
0,1,Manajemen Keuangan,MANAJEMEN,Course introduction: \n\nSelamat datang di mat...
1,1,Manajemen Keuangan,MANAJEMEN,Manajemen Keuangan (NK) adalah mata kuliah yan...
2,1,Manajemen Keuangan,MANAJEMEN,Course introduction: \n\nSelamat datang di mat...
3,1,Manajemen Keuangan,MANAJEMEN,Manajemen Keuangan (NK) adalah mata kuliah yan...
4,1,Manajemen Sumber Daya Manusia,MANAJEMEN,Course Introduction:\n\nSelamat datang di mata...

In [9]:
df_cleaned = df.drop_duplicates(subset=['Mata Kuliah', 'Major'], keep='first')
df_cleaned

,ID,Mata Kuliah,Major,Description
0,1,Manajemen Keuangan,MANAJEMEN,Course introduction: \n\nSelamat datang di mat...
4,1,Manajemen Sumber Daya Manusia,MANAJEMEN,Course Introduction:\n\nSelamat datang di mata...
5,1,Manajemen Pemasaran,MANAJEMEN,Halo! Selamat datang di course introduction un...
6,1,Manajemen Operasional,MANAJEMEN,"Manajemen Operasional, atau yang juga dikenal ..."
7,1,Manajemen Strategi,MANAJEMEN,Course Introduction:\n\nSelamat datang di mata...
...,...,...,...,...
1300,240,Dasar-dasar Elektronika,TEKNIK TENAGA LISTRIK,Deskripsi mata kuliah Dasar-dasar Elektronika ...
1301,240,Teknik Instalasi Listrik,TEKNIK TENAGA LISTRIK,Deskripsi Mata Kuliah Teknik Instalasi Listrik...
1302,240,Sistem Pembangkit Tenaga Listrik,TEKNIK TENAGA LISTRIK,Course Introduction: Mata kuliah ini bertujuan...
1303,240,Pengantar Sistem Tenaga Listrik,TEKNIK TENAGA LISTRIK,Mata kuliah Pengantar Sistem Tenaga Listrik me...
1304,240,Teknik Proteksi Listrik,TEKNIK TENAGA LISTRIK,Mata kuliah Teknik Proteksi Listrik merupakan ...

In [10]:
df_cleaned.to_csv('../dataset/course_cleaned.csv', index=False)