In [36]:
# !pip install pandas
# !pip list

In [37]:
import pandas as pd

data = pd.read_csv('major_data_cleaned_300.csv')
data

,NAMA,PEMINAT 2023,Description,Mata Kuliah,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,...,Bisnis dan Ekonomi,Seni,Sastra dan Linguistik,Pendidikan,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum
0,MANAJEMEN,84340,MANAJEMEN adalah jurusan yang mempelajari teo...,1. Manajemen Keuangan\n2. Manajemen Sumber Day...,0.30,0.0,0.0,0.3,0.0,0.0,...,0.9,0.2,0.1,0.1,0.10,0.1,0.1,0.5,0.1,0.1
1,AKUNTANSI,63257,Jurusan Akuntansi adalah salah satu jurusan da...,1. Akuntansi Keuangan\n2. Akuntansi Biaya\n3. ...,0.60,0.0,0.1,0.1,0.1,0.0,...,0.6,0.1,0.1,0.1,0.10,0.1,0.1,0.3,0.1,0.4
2,ILMU KOMUNIKASI,57627,Jurusan Ilmu Komunikasi adalah salah satu jur...,1. Teori Komunikasi\n2. Jurnalistik\n3. Public...,0.10,0.1,0.1,0.4,0.1,0.1,...,0.4,0.3,0.3,0.1,0.10,0.1,0.1,0.9,0.1,0.3
3,PSIKOLOGI,54772,Jurusan Psikologi adalah cabang ilmu yang memp...,1. Psikologi Klinis\n2. Psikologi Industri\n3....,0.30,0.4,0.1,0.3,0.3,0.1,...,0.1,0.1,0.1,0.2,0.30,0.8,0.1,0.3,0.3,0.2
4,ILMU HUKUM,44576,Jurusan Ilmu Hukum adalah salah satu jurusan d...,1. Hukum Acara Perdata\n2. Hukum Acara Pidana\...,0.10,0.1,0.1,0.4,0.1,0.1,...,0.2,0.1,0.2,0.1,0.10,0.1,0.1,0.4,0.1,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,TEKNOLOGI SAINS DATA,645,Teknologi Sains Data merupakan jurusan kuliah ...,1. Matematika Dasar\n2. Data Mining\n3. Statis...,0.55,0.7,0.2,0.2,0.3,0.1,...,0.5,0.2,0.1,0.2,0.20,0.4,0.2,0.3,0.1,0.2
290,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,644,Jurusan kuliah Matematika di Fakultas Matemati...,1. Kalkulus\n2. Aljabar Linear\n3. Fisika Dasa...,0.80,0.8,0.6,0.2,0.3,0.4,...,0.3,0.2,0.2,0.4,0.45,0.2,0.4,0.1,0.3,0.2
291,PENDIDIKAN TEKNOLOGI INFORMATIKA DAN KOMPUTER,644,Jurusan Pendidikan Teknologi Informasi dan Kom...,1. Algoritma dan Pemrograman\n2. Pemrograman W...,0.65,0.3,0.2,0.1,0.2,0.1,...,0.4,0.1,0.1,0.7,0.10,0.2,0.1,0.2,0.2,0.1
292,TEKNOLOGI BIOPROSES,639,Teknologi Bioproses adalah cabang ilmu yang me...,1. Teknik Proses\n2. Mikrobiologi Industri\n3....,0.40,0.3,0.3,0.0,0.8,0.5,...,0.2,0.1,0.0,0.3,0.80,0.2,0.2,0.1,0.2,0.1
293,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,637,Jurusan kuliah FMIPA-IPA adalah salah satu jur...,1. Matematika Dasar\n2. Fisika Dasar\n3. Kimia...,0.60,0.5,0.6,0.2,0.8,0.6,...,0.3,0.1,0.1,0.2,0.50,0.2,0.2,0.1,0.2,0.2

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAMA                   294 non-null    object
 1   PEMINAT 2023           294 non-null    int64
 2   Description            294 non-null    object
 3   Mata Kuliah            294 non-null    object
 4   Matematika             294 non-null    float64
 5   Sains                  294 non-null    float64
 6   Fisika                 294 non-null    float64
 7   Sosiologi              294 non-null    float64
 8   Biologi                294 non-null    float64
 9   Kimia                  294 non-null    float64
 10  Teknologi              294 non-null    float64
 11  Bisnis dan Ekonomi     294 non-null    float64
 12  Seni                   294 non-null    float64
 13  Sastra dan Linguistik  294 non-null    float64
 14  Pendidikan             294 non-null    float64
 15  Lingkungan             294 non-null    float64
 16  Kesehatan              294 non-null    float64
 17  Geografi               294 non-null    float64
 18  Komunikasi             294 non-null    float64
 19  Sejarah dan Filsafat   294 non-null    float64
 20  Hukum                  294 non-null    float64
dtypes: float64(17), int64(1), object(3)
memory usage: 48.4+ KB

In [39]:
data['Matematika'] = data['Matematika'].astype(float)
data['Sains'] = data['Sains'].astype(float)
data['Fisika'] = data['Fisika'].astype(float)
data['Sosiologi'] = data['Sosiologi'].astype(float)
data['Biologi'] = data['Biologi'].astype(float)
data['Kimia'] = data['Kimia'].astype(float)
data['Bisnis dan Ekonomi'] = data['Bisnis dan Ekonomi'].astype(float)
data['Teknologi'] = data['Teknologi'].astype(float)
data['Seni'] = data['Seni'].astype(float)
data['Sastra dan Linguistik'] = data['Sastra dan Linguistik'].astype(float)
data['Pendidikan'] = data['Pendidikan'].astype(float)
data['Hukum'] = data['Hukum'].astype(float)
data['Lingkungan'] = data['Lingkungan'].astype(float)
data['Kesehatan'] = data['Kesehatan'].astype(float)
data['Geografi'] = data['Geografi'].astype(float)
data['Komunikasi'] = data['Komunikasi'].astype(float)
data['Sejarah dan Filsafat'] = data['Sejarah dan Filsafat'].astype(float)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAMA                   294 non-null    object
 1   PEMINAT 2023           294 non-null    int64
 2   Description            294 non-null    object
 3   Mata Kuliah            294 non-null    object
 4   Matematika             294 non-null    float64
 5   Sains                  294 non-null    float64
 6   Fisika                 294 non-null    float64
 7   Sosiologi              294 non-null    float64
 8   Biologi                294 non-null    float64
 9   Kimia                  294 non-null    float64
 10  Teknologi              294 non-null    float64
 11  Bisnis dan Ekonomi     294 non-null    float64
 12  Seni                   294 non-null    float64
 13  Sastra dan Linguistik  294 non-null    float64
 14  Pendidikan             294 non-null    float64
 15  Lingkungan             294 non-null    float64
 16  Kesehatan              294 non-null    float64
 17  Geografi               294 non-null    float64
 18  Komunikasi             294 non-null    float64
 19  Sejarah dan Filsafat   294 non-null    float64
 20  Hukum                  294 non-null    float64
dtypes: float64(17), int64(1), object(3)
memory usage: 48.4+ KB

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAMA                   294 non-null    object
 1   PEMINAT 2023           294 non-null    int64
 2   Description            294 non-null    object
 3   Mata Kuliah            294 non-null    object
 4   Matematika             294 non-null    float64
 5   Sains                  294 non-null    float64
 6   Fisika                 294 non-null    float64
 7   Sosiologi              294 non-null    float64
 8   Biologi                294 non-null    float64
 9   Kimia                  294 non-null    float64
 10  Teknologi              294 non-null    float64
 11  Bisnis dan Ekonomi     294 non-null    float64
 12  Seni                   294 non-null    float64
 13  Sastra dan Linguistik  294 non-null    float64
 14  Pendidikan             294 non-null    float64
 15  Lingkungan             294 non-null    float64
 16  Kesehatan              294 non-null    float64
 17  Geografi               294 non-null    float64
 18  Komunikasi             294 non-null    float64
 19  Sejarah dan Filsafat   294 non-null    float64
 20  Hukum                  294 non-null    float64
dtypes: float64(17), int64(1), object(3)
memory usage: 48.4+ KB

In [41]:
data.describe()

,PEMINAT 2023,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,Teknologi,Bisnis dan Ekonomi,Seni,Sastra dan Linguistik,Pendidikan,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum
count,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000
mean,4752.010204,0.329762,0.289116,0.189286,0.229592,0.210204,0.144218,0.272959,0.284354,0.182993,0.136054,0.322789,0.225510,0.205782,0.197279,0.294558,0.182313,0.211905
std,9685.873336,0.236312,0.247204,0.206496,0.177656,0.238771,0.172516,0.245558,0.257634,0.201699,0.212877,0.273876,0.205585,0.249472,0.184722,0.199755,0.181462,0.200582
min,637.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,943.500000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.000000,0.100000,0.100000,0.100000,0.100000,0.200000,0.100000,0.100000
50%,1586.500000,0.250000,0.200000,0.100000,0.200000,0.100000,0.100000,0.200000,0.200000,0.100000,0.100000,0.200000,0.200000,0.100000,0.200000,0.275000,0.200000,0.200000
75%,3210.750000,0.500000,0.400000,0.200000,0.300000,0.300000,0.100000,0.300000,0.400000,0.200000,0.100000,0.500000,0.300000,0.200000,0.200000,0.400000,0.200000,0.300000
max,84340.000000,1.000000,1.000000,1.000000,0.900000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.900000,1.000000,1.000000,0.900000,0.900000,0.900000

In [42]:
data['Description'].head()

0     MANAJEMEN adalah jurusan yang mempelajari teo...
1    Jurusan Akuntansi adalah salah satu jurusan da...
2     Jurusan Ilmu Komunikasi adalah salah satu jur...
3    Jurusan Psikologi adalah cabang ilmu yang memp...
4    Jurusan Ilmu Hukum adalah salah satu jurusan d...
Name: Description, dtype: object

In [43]:
data['Mata Kuliah'].head()

0    1. Manajemen Keuangan\n2. Manajemen Sumber Day...
1    1. Akuntansi Keuangan\n2. Akuntansi Biaya\n3. ...
2    1. Teori Komunikasi\n2. Jurnalistik\n3. Public...
3    1. Psikologi Klinis\n2. Psikologi Industri\n3....
4    1. Hukum Acara Perdata\n2. Hukum Acara Pidana\...
Name: Mata Kuliah, dtype: object

In [44]:
# def split_mata_kuliah(mata_kuliah):
#     mata_kuliah_list = mata_kuliah.split('\n')
#     mata_kuliah_list = [mk.split('. ', 1)[1] if '. ' in mk else mk for mk in mata_kuliah_list]
#     return mata_kuliah_list

# only takes 5 courses
def split_mata_kuliah(mata_kuliah):
    mata_kuliah_list = mata_kuliah.split('\n')
    mata_kuliah_list = mata_kuliah_list[:5]
    mata_kuliah_list = [mk.split('. ', 1)[1] if '. ' in mk else mk for mk in mata_kuliah_list]
    return mata_kuliah_list

In [45]:
data['Split Mata Kuliah'] = data['Mata Kuliah'].apply(split_mata_kuliah)
# data['Split Mata Kuliah'] = data['Split Mata Kuliah'][:5]

# data_exploded = data.explode('Split Mata Kuliah').reset_index(drop=True)
# data_exploded = data.explode('Split Mata Kuliah').reset_index(drop=True)

In [46]:
# data['Split Mata Kuliah'] = data['Split Mata Kuliah'][:5]

In [47]:
data_exploded = data.explode('Split Mata Kuliah').reset_index(drop=True)

In [48]:
data_exploded

,NAMA,PEMINAT 2023,Description,Mata Kuliah,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,...,Seni,Sastra dan Linguistik,Pendidikan,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum,Split Mata Kuliah
0,MANAJEMEN,84340,MANAJEMEN adalah jurusan yang mempelajari teo...,1. Manajemen Keuangan\n2. Manajemen Sumber Day...,0.3,0.0,0.0,0.3,0.0,0.0,...,0.2,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,Manajemen Keuangan
1,MANAJEMEN,84340,MANAJEMEN adalah jurusan yang mempelajari teo...,1. Manajemen Keuangan\n2. Manajemen Sumber Day...,0.3,0.0,0.0,0.3,0.0,0.0,...,0.2,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,Manajemen Sumber Daya Manusia
2,MANAJEMEN,84340,MANAJEMEN adalah jurusan yang mempelajari teo...,1. Manajemen Keuangan\n2. Manajemen Sumber Day...,0.3,0.0,0.0,0.3,0.0,0.0,...,0.2,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,Manajemen Pemasaran
3,MANAJEMEN,84340,MANAJEMEN adalah jurusan yang mempelajari teo...,1. Manajemen Keuangan\n2. Manajemen Sumber Day...,0.3,0.0,0.0,0.3,0.0,0.0,...,0.2,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,Manajemen Operasional
4,MANAJEMEN,84340,MANAJEMEN adalah jurusan yang mempelajari teo...,1. Manajemen Keuangan\n2. Manajemen Sumber Day...,0.3,0.0,0.0,0.3,0.0,0.0,...,0.2,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,Manajemen Strategi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,637,Jurusan kuliah FMIPA-IPA adalah salah satu jur...,1. Matematika Dasar\n2. Fisika Dasar\n3. Kimia...,0.6,0.5,0.6,0.2,0.8,0.6,...,0.1,0.1,0.2,0.5,0.2,0.2,0.1,0.2,0.2,Matematika Dasar
1466,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,637,Jurusan kuliah FMIPA-IPA adalah salah satu jur...,1. Matematika Dasar\n2. Fisika Dasar\n3. Kimia...,0.6,0.5,0.6,0.2,0.8,0.6,...,0.1,0.1,0.2,0.5,0.2,0.2,0.1,0.2,0.2,Fisika Dasar
1467,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,637,Jurusan kuliah FMIPA-IPA adalah salah satu jur...,1. Matematika Dasar\n2. Fisika Dasar\n3. Kimia...,0.6,0.5,0.6,0.2,0.8,0.6,...,0.1,0.1,0.2,0.5,0.2,0.2,0.1,0.2,0.2,Kimia Dasar
1468,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,637,Jurusan kuliah FMIPA-IPA adalah salah satu jur...,1. Matematika Dasar\n2. Fisika Dasar\n3. Kimia...,0.6,0.5,0.6,0.2,0.8,0.6,...,0.1,0.1,0.2,0.5,0.2,0.2,0.1,0.2,0.2,Biologi Dasar
1469,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,637,Jurusan kuliah FMIPA-IPA adalah salah satu jur...,1. Matematika Dasar\n2. Fisika Dasar\n3. Kimia...,0.6,0.5,0.6,0.2,0.8,0.6,...,0.1,0.1,0.2,0.5,0.2,0.2,0.1,0.2,0.2,Statistika

In [49]:
# import re
# new_data = data.copy()
# new_data['Mata Kuliah'] = new_data['Mata Kuliah'].apply(lambda x: re.sub(r'^\d+\.\s', '', x))
# # new_data['Split matkul'] = new_data['Mata Kuliah'].apply(lambda x: re.sub(r'^\d+\.\s', '', x))
# # new_data['Split matkul'] = new_data['Split matkul'].apply(lambda x: re.sub(r'\n', '', x))
# new_data

In [50]:
data_courses = data_exploded[['Split Mata Kuliah', 'NAMA', 'Matematika', 'Sains', 'Fisika', 'Sosiologi', 'Biologi', 'Kimia', 'Bisnis dan Ekonomi', 'Teknologi', 'Seni', 'Sastra dan Linguistik', 'Pendidikan', 'Hukum', 'Lingkungan', 'Kesehatan', 'Geografi', 'Komunikasi', 'Sejarah dan Filsafat', 'Hukum']]
data_courses

,Split Mata Kuliah,NAMA,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,Bisnis dan Ekonomi,Teknologi,Seni,Sastra dan Linguistik,Pendidikan,Hukum,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum
0,Manajemen Keuangan,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
1,Manajemen Sumber Daya Manusia,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
2,Manajemen Pemasaran,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
3,Manajemen Operasional,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
4,Manajemen Strategi,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,Matematika Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1466,Fisika Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1467,Kimia Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1468,Biologi Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1469,Statistika,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2

In [51]:
data_courses

,Split Mata Kuliah,NAMA,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,Bisnis dan Ekonomi,Teknologi,Seni,Sastra dan Linguistik,Pendidikan,Hukum,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum
0,Manajemen Keuangan,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
1,Manajemen Sumber Daya Manusia,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
2,Manajemen Pemasaran,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
3,Manajemen Operasional,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
4,Manajemen Strategi,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,Matematika Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1466,Fisika Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1467,Kimia Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1468,Biologi Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2
1469,Statistika,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2

In [52]:
data_courses.drop_duplicates(subset='Split Mata Kuliah', inplace=True)
data_courses.reset_index(drop=True, inplace=True)
data_courses

/var/folders/nq/594j5_s93zb26q0lb90lzh0r0000gn/T/ipykernel_2081/1300989572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_courses.drop_duplicates(subset='Split Mata Kuliah', inplace=True)

,Split Mata Kuliah,NAMA,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,Bisnis dan Ekonomi,Teknologi,Seni,Sastra dan Linguistik,Pendidikan,Hukum,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum
0,Manajemen Keuangan,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
1,Manajemen Sumber Daya Manusia,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
2,Manajemen Pemasaran,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
3,Manajemen Operasional,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
4,Manajemen Strategi,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,Teknik Proses,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,0.1,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1
935,Mikrobiologi Industri,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,0.1,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1
936,Pemodelan Proses,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,0.1,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1
937,Rekayasa Protein,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,0.1,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1
938,Biologi Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,0.1,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2

In [53]:
data_courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Split Mata Kuliah      939 non-null    object
 1   NAMA                   939 non-null    object
 2   Matematika             939 non-null    float64
 3   Sains                  939 non-null    float64
 4   Fisika                 939 non-null    float64
 5   Sosiologi              939 non-null    float64
 6   Biologi                939 non-null    float64
 7   Kimia                  939 non-null    float64
 8   Bisnis dan Ekonomi     939 non-null    float64
 9   Teknologi              939 non-null    float64
 10  Seni                   939 non-null    float64
 11  Sastra dan Linguistik  939 non-null    float64
 12  Pendidikan             939 non-null    float64
 13  Hukum                  939 non-null    float64
 14  Lingkungan             939 non-null    float64
 15  Kesehatan              939 non-null    float64
 16  Geografi               939 non-null    float64
 17  Komunikasi             939 non-null    float64
 18  Sejarah dan Filsafat   939 non-null    float64
 19  Hukum                  939 non-null    float64
dtypes: float64(18), object(2)
memory usage: 146.8+ KB

In [54]:
columns_to_consider = ['Matematika', 'Sains', 'Fisika', 'Sosiologi', 'Biologi', 'Kimia',
                       'Bisnis dan Ekonomi', 'Teknologi', 'Seni', 'Sastra dan Linguistik',
                       'Pendidikan', 'Hukum', 'Lingkungan', 'Kesehatan', 'Geografi',
                       'Komunikasi', 'Sejarah dan Filsafat']

index_mapping = {column: index+1 for index, column in enumerate(columns_to_consider)}

# Find the column with the maximum value for each row
max_columns = data_courses[columns_to_consider].idxmax(axis=1)

# Map the column names to their respective index values
data_courses['highest'] = max_columns.map(index_mapping)

/var/folders/nq/594j5_s93zb26q0lb90lzh0r0000gn/T/ipykernel_2081/3164568918.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_courses['highest'] = max_columns.map(index_mapping)

In [55]:
data_courses

,Split Mata Kuliah,NAMA,Matematika,Sains,Fisika,Sosiologi,Biologi,Kimia,Bisnis dan Ekonomi,Teknologi,...,Sastra dan Linguistik,Pendidikan,Hukum,Lingkungan,Kesehatan,Geografi,Komunikasi,Sejarah dan Filsafat,Hukum,highest
0,Manajemen Keuangan,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,...,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,7
1,Manajemen Sumber Daya Manusia,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,...,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,7
2,Manajemen Pemasaran,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,...,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,7
3,Manajemen Operasional,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,...,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,7
4,Manajemen Strategi,MANAJEMEN,0.3,0.0,0.0,0.3,0.0,0.0,0.9,0.3,...,0.1,0.1,0.1,0.1,0.1,0.1,0.5,0.1,0.1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,Teknik Proses,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,...,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1,5
935,Mikrobiologi Industri,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,...,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1,5
936,Pemodelan Proses,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,...,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1,5
937,Rekayasa Protein,TEKNOLOGI BIOPROSES,0.4,0.3,0.3,0.0,0.8,0.5,0.2,0.1,...,0.0,0.3,0.1,0.8,0.2,0.2,0.1,0.2,0.1,5
938,Biologi Dasar,FAKULTAS MATEMATIKA DAN ILMU PENGETAHUAN ALAM ...,0.6,0.5,0.6,0.2,0.8,0.6,0.3,0.6,...,0.1,0.2,0.2,0.5,0.2,0.2,0.1,0.2,0.2,5

In [56]:
data_courses.to_csv('course_data_cleaned.csv', index=False)